### ISSUE TITLE
Dedicated aux-mix views

### ISSUE THREAD

**Issue by ahellquist** [ovenwerks/ardour-touchOSC#1]
Hardware mixers and other similar equipment features dedicated monitor mix views that musicians can point there devices to to alter there own monitor mix.

Some people uses Ardour for live mixing by using busses and sends to send personal mixes to in-ear monitors for musicians and would really appreciate such a "limited" view

I am not sure the OSC layer is the best place to implement this function though but I wanted to put the feature request here anyway.

**Comment by ovenwerks** [comment]
This has already been implemented for a while, see: http://manual.ardour.org/using-control-surfaces/controlling-ardour-with-osc/osc-personal-monitoring/ there is in this repo a touchosc map called personal_phn which allows a performer to just see the channels feeding there aux channel.
