### ISSUE TITLE
Banksize

### ISSUE THREAD

**Issue by sciurius** [ovenwerks/ardour-touchOSC#3]
According to the README, the banksize in Ardour must be set to 8. Hoewever, this causes only the first 8 track names (and other info?) to be loaded.
Setting the banksize to 24 fixes this.

**Comment by ovenwerks** [comment]
Because there is more than one map/layout and they all have different bank sizes, please include the layout name you are talking about. I think I fixed the right one. but I am not sure.

**Comment by sciurius** [comment]
Sorry!
It is the 24 channel 1 fader layout.
