### ISSUE TITLE
Slider feedback

### ISSUE THREAD

**Issue by sciurius** [ovenwerks/ardour-touchOSC#4]
When a track is selected, the mixer controls are not updated to show the properties of the selected track.

Also, when I move the slider in Ardour, its position is not updated on the tablet.

**Comment by ovenwerks** [comment]
These are both the same problem. TouchOSC needs to be set up with two ports that work with Ardour. The port that touchOSC uses to talk to  Ardour should be 3819, the port that Ardour uses to feedback to touchOSC is probably defaulted to 8000 and touch OSC needs to have it's setting reflect this. So in touchOSC setting->OSC there is port (outgoing): 3819 and port(incoming): 8000.
Then in Ardour preferences->control surfaces with Open Sound Control highlighted select: Show protocol settings. A dialog will pop up and make sure the reply manual port is also set to 8000.
I don't know which layout you are using and so can't comment further, but I think I have put a "connect" button on almost all of them. If not a bank up or down should also work to connect. My personal monitoring layout uses next/previous this way.

**Comment by sciurius** [comment]
It is the 24-channel 1 fader layout.
The port is not the issue (I do use two ports 3819 and 9000).
And it is just the mixer controls that do not update. The track button and its collection of leds function properly so feedback is functional.

**Comment by ovenwerks** [comment]
Is this fixed in your new(er) layout or is it still an issue?

**Comment by sciurius** [comment]
I can't reproduce this anymore so apparently it was fixed...
